# Generated by Django 4.2.3 on 2024-05-19 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StockDayBar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("ticker", models.CharField(max_length=12)),
                ("timestamp", models.DateField(blank=True, null=True)),
                ("open_price", models.FloatField()),
                ("close_price", models.FloatField()),
                ("highest_price", models.FloatField()),
                ("lowest_price", models.FloatField()),
                ("tx_quantity", models.FloatField()),
            ],
        ),
    ]
