# Generated by Django 4.2.3 on 2024-05-19 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocksapi", "0002_profitandloss_stockdailybar_delete_stockdaybar_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profitandloss",
            name="ticker",
            field=models.CharField(default="", max_length=12),
        ),
    ]
