# Generated by Django 4.2.3 on 2024-05-19 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocksapi", "0003_profitandloss_ticker"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockdailybar",
            name="timestamp",
            field=models.DateField(blank=True, null=True),
        ),
    ]
